/home/pumpkin/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py:446: UserWarning: Using a target size (torch.Size([16, 3, 80, 80])) that is different to the input size (torch.Size([16, 8, 80, 80])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Net(
  (conv1): Conv2d(1, 8, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (conv2): Conv2d(8, 8, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (relu): ReLU()
)
training begins
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/pumpkin/anaconda3/envs/483/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/pumpkin/anaconda3/envs/483/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/pumpkin/anaconda3/envs/483/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    status_response = self._interface.communicate_stop_status()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 378, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    self.run()    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
  File "/home/pumpkin/anaconda3/envs/483/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 388, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
device: cuda:0
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7fa4a02593a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7fa4a0259160> (for pre_run_cell):
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.