2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_setup.py:_flush():71] setting env: {}
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_init.py:_log_setup():371] Logging user logs to /home/pumpkin/.git/CENG-483/hw/hw3/implementation/src/wandb/wandb/run-20220124_162816-2mjavvho/logs/debug.log
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_init.py:_log_setup():372] Logging internal logs to /home/pumpkin/.git/CENG-483/hw/hw3/implementation/src/wandb/wandb/run-20220124_162816-2mjavvho/logs/debug-internal.log
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_init.py:init():404] calling init triggers
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'epochs': 100, 'batch_size': 16, 'learning_rate': 1.0, 'architecture': 'CNN'}
2022-01-24 16:28:16,562 INFO    MainThread:49393 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 1cn2tw3a
2022-01-24 16:28:16,563 INFO    MainThread:49393 [wandb_run.py:finish():1457] finishing run alpayozkan/vision/1cn2tw3a
2022-01-24 16:28:16,563 INFO    MainThread:49393 [jupyter.py:save_history():429] not saving jupyter history
2022-01-24 16:28:16,563 INFO    MainThread:49393 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-24 16:28:16,563 INFO    MainThread:49393 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-24 16:28:16,564 INFO    MainThread:49393 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-24 16:28:16,564 INFO    MainThread:49393 [wandb_run.py:_restore():1752] restore
2022-01-24 16:28:17,535 INFO    MainThread:49393 [wandb_run.py:_restore():1752] restore
2022-01-24 16:28:17,544 ERROR   MainThread:49393 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
